-- Create visitor_analytics table for tracking website visitors
CREATE TABLE IF NOT EXISTS visitor_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) UNIQUE NOT NULL,
    ip_address INET,
    user_agent TEXT,
    referrer VARCHAR(500),
    landing_page VARCHAR(500),
    exit_page VARCHAR(500),
    page_type VARCHAR(50) DEFAULT 'other',
    page_views INTEGER DEFAULT 1,
    duration_seconds INTEGER DEFAULT 0,
    is_return_visitor BOOLEAN DEFAULT FALSE,
    visit_date DATE NOT NULL,
    visit_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_visitor_analytics_session_id ON visitor_analytics(session_id);
CREATE INDEX IF NOT EXISTS idx_visitor_analytics_visit_date ON visitor_analytics(visit_date);
CREATE INDEX IF NOT EXISTS idx_visitor_analytics_visit_time ON visitor_analytics(visit_time);
CREATE INDEX IF NOT EXISTS idx_visitor_analytics_is_return_visitor ON visitor_analytics(is_return_visitor);

-- Add RLS (Row Level Security) policies
ALTER TABLE visitor_analytics ENABLE ROW LEVEL SECURITY;

-- Policy to allow authenticated users to read visitor analytics
CREATE POLICY "Authenticated users can view visitor analytics" ON visitor_analytics
    FOR SELECT USING (auth.role() = 'authenticated');

-- Policy to allow anonymous inserts (for tracking visitors)
CREATE POLICY "Allow anonymous visitor tracking" ON visitor_analytics
    FOR INSERT WITH CHECK (true);

-- Policy to allow authenticated users to update visitor analytics
CREATE POLICY "Authenticated users can update visitor analytics" ON visitor_analytics
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_visitor_analytics_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger to automatically update updated_at
CREATE TRIGGER visitor_analytics_updated_at
    BEFORE UPDATE ON visitor_analytics
    FOR EACH ROW
    EXECUTE FUNCTION update_visitor_analytics_updated_at();
